---
runners:
  plugin: threaded
  options:
    num_workers: 10

logging:
  enabled: False

inventory:
  plugin: SimpleInventory
  options:
    host_file: "inventories/inventory-10-csr-local/hosts.yaml"
    group_file: "inventories/inventory-10-csr-local/groups.yaml"
    defaults_file: "inventories/inventory-10-csr-local/defaults.yaml"
